name: mugu
description: Monster hunter gathering hub

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  awesome_select: ^5.2.0
  flow_builder: ^0.0.8
  after_layout: ^1.2.0
  shared_preferences: ^2.0.15
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/

  uses-material-design: true
